### ISSUE TITLE
Using $this when not in object context

### ISSUE THREAD

**Issue by LeonB** [jmarcher/valet-linux#36]
``` shell
$ valet
PHP Fatal error:  Uncaught Error: Using $this when not in object context in /home/leon/.dotfiles/.composer/vendor/jmarcher/valet-linux/cli/Valet/Valet.php:60
Stack trace:
#0 /home/leon/.dotfiles/.composer/vendor/jmarcher/valet-linux/cli/includes/facades.php(25): Valet\Valet::extensions()
#1 /home/leon/.dotfiles/.composer/vendor/jmarcher/valet-linux/cli/valet.php(275): Facade::__callStatic('extensions', Array)
#2 {main}
  thrown in /home/leon/.dotfiles/.composer/vendor/jmarcher/valet-linux/cli/Valet/Valet.php on line 60
```

``` shell
$ dpkg -l |grep php
ii  php-common                                  1:35ubuntu6                                   all          Common files for PHP packages
ii  php7.0-bcmath                               7.0.8-0ubuntu0.16.04.3                        amd64        Bcmath module for PHP
ii  php7.0-bz2                                  7.0.8-0ubuntu0.16.04.3                        amd64        bzip2 module for PHP
ii  php7.0-cli                                  7.0.8-0ubuntu0.16.04.3                        amd64        command-line interpreter for the PHP scripting language
ii  php7.0-common                               7.0.8-0ubuntu0.16.04.3                        amd64        documentation, examples and common module for PHP
ii  php7.0-curl                                 7.0.8-0ubuntu0.16.04.3                        amd64        CURL module for PHP
ii  php7.0-fpm                                  7.0.8-0ubuntu0.16.04.3                        amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.0-gd                                   7.0.8-0ubuntu0.16.04.3                        amd64        GD module for PHP
ii  php7.0-intl                                 7.0.8-0ubuntu0.16.04.3                        amd64        Internationalisation module for PHP
ii  php7.0-json                                 7.0.8-0ubuntu0.16.04.3                        amd64        JSON module for PHP
ii  php7.0-mbstring                             7.0.8-0ubuntu0.16.04.3                        amd64        MBSTRING module for PHP
ii  php7.0-mcrypt                               7.0.8-0ubuntu0.16.04.3                        amd64        libmcrypt module for PHP
ii  php7.0-opcache                              7.0.8-0ubuntu0.16.04.3                        amd64        Zend OpCache module for PHP
ii  php7.0-readline                             7.0.8-0ubuntu0.16.04.3                        amd64        readline module for PHP
ii  php7.0-soap                                 7.0.8-0ubuntu0.16.04.3                        amd64        SOAP module for PHP
ii  php7.0-sqlite3                              7.0.8-0ubuntu0.16.04.3                        amd64        SQLite3 module for PHP
ii  php7.0-tidy                                 7.0.8-0ubuntu0.16.04.3                        amd64        tidy module for PHP
ii  php7.0-xml                                  7.0.8-0ubuntu0.16.04.3                        amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.0-zip                                  7.0.8-0ubuntu0.16.04.3                        amd64        Zip module for PHP
```

**Comment by LeonB** [comment]
Valet v2.0.10 works.

**Comment by LeonB** [comment]
With version 2.1, If I do `composer global remove phpmetrics/phpmetrics` it works.
As soon as I install `phpmetrics/phpmetrics` it breaks again.

**Comment by jmarcher** [comment]
Will have to take a look what are the conflicts with phpmetrics/phpmetrics

**Comment by LeonB** [comment]
I've managed to pinpoint it to a dependency of phpmetrics: hoa/wrapper

This is it:

``` php
namespace
{

/**
 * Alias of `Hoa\Protocol::resolve` method.
 *
 * @param   string  $path      Path to resolve.
 * @param   bool    $exists    If `true`, try to find the first that exists,
 *                             else return the first solution.
 * @param   bool    $unfold    Return all solutions instead of one.
 * @return  mixed
 */
if (!function_exists('resolve')) {
    function resolve($path, $exists = true, $unfold = false)
    {
        return Hoa\Protocol::getInstance()->resolve($path, $exists, $unfold);
    }
}

}
```

in `hoa/protocol/Wrapper.php`

**Comment by LeonB** [comment]
https://github.com/hoaproject/Protocol/issues/18
